#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    military_time = ''
    if s[-2:] == 'PM':
        if s[:2] == '12': 
            return s[:-2]
        hour = int(s[:2]) + 12
        return '{}{}'.format(hour, s[2:-2])
    
    if s[:2] != '12': 
        return s[:-2]
    return '00{}'.format(s[2:-2])


s = '07:05:45PM'
timeConversion(s)
  
